version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/calculator"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(calculator)"
  - package-ecosystem: "cargo"
    directory: "/gui"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(gui)"
  - package-ecosystem: "cargo"
    directory: "/cli"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(cli)"
