name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  ffi: ^2.1.0
  after_layout: ^1.2.0
  google_fonts: ^6.1.0
  linked_scroll_controller: ^0.2.0
  intersperse: ^2.0.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  ffigen: ^8.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
