name: CD

on:
  push:
    tags: "*"

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v1
      - name: Run Tests
        run: cargo test
      - name: Build
        run: cargo build --bin cli --release && cargo build --bin gui --release && cargo build --bin discord --release
      - name: Rename
        run: mv ./target/release/cli ./target/release/cli-linux &&  mv ./target/release/gui ./target/release/gui-linux
      - name: Upload CLI
        uses: actions/upload-artifact@v3
        with:
          name: cli-linux
          path: ./target/release/cli-linux
          if-no-files-found: error
      - name: Upload GUI
        uses: actions/upload-artifact@v3
        with:
          name: gui-linux
          path: ./target/release/gui-linux
          if-no-files-found: error

  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v1
      - name: Run Tests
        run: cargo test
      - name: Build
        run: cargo build --bin cli --release && cargo build --bin gui --release && cargo build --bin discord --release
      - name: Rename
        run: mv ./target/release/cli.exe ./target/release/cli-windows.exe &&  mv ./target/release/gui.exe ./target/release/gui-windows.exe
      - name: Upload CLI
        uses: actions/upload-artifact@v3
        with:
          name: cli-windows
          path: ./target/release/cli-windows.exe
          if-no-files-found: error
      - name: Upload GUI
        uses: actions/upload-artifact@v3
        with:
          name: gui-windows
          path: ./target/release/gui-windows.exe
          if-no-files-found: error

  build-macos:
    name: Macos Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v1
      - name: Run Tests
        run: cargo test
      - name: Build
        run: cargo build --bin cli --release && cargo build --bin gui --release && cargo build --bin discord --release
      - name: Rename
        run: mv ./target/release/cli ./target/release/cli-macos &&  mv ./target/release/gui ./target/release/gui-macos
      - name: Upload CLI
        uses: actions/upload-artifact@v3
        with:
          name: cli-macos
          path: ./target/release/cli-macos
          if-no-files-found: error
      - name: Upload GUI
        uses: actions/upload-artifact@v3
        with:
          name: gui-macos
          path: ./target/release/gui-macos
          if-no-files-found: error

  release:
    name: Release
    if: github.repository == 'david072/calculator'
    needs: [ build-linux, build-windows, build-macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Version
        id: get_release
        run: echo ::set-output name=version::${GITHUB_REF:10}
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            # Changes
            ## Fixed
            - TODO
            ## Changed
            - TODO
            ## Added
            - TODO
          files: |
            gui-linux/gui-linux
            gui-windows/gui-windows.exe
            gui-macos/gui-macos
            cli-linux/cli-linux
            cli-windows/cli-windows.exe
            cli-macos/cli-macos
          fail_on_unmatched_files: true
          draft: true
